#!/usr/bin/env bash

cd /autograder/source
rm /autograder/source/src/edu/umass/cics/cs187/structures/RecursiveList.java
cp /autograder/submission/RecursiveList.java /autograder/source/src/edu/umass/cics/cs187/structures/

# compilation
sh compile.sh

# execution
sh run.sh